from .weather_page import WeatherPage
from .reminder_page import ReminderPage
from .learning_page import LearningPage
from .homework_page import HomeworkPage
from .fitness_page import FitnessPage
from .sitting_posture_page import SittingPosturePage
from .student_clockin_page import StudentClockinPage
from .pomodoro_page import PomodoroPage
from .image_studio_page import ImageStudioPage
from .security_inspection_page import SecurityInspectionPage
from .video_page import VideoPage
from .placeholder_page import PlaceholderPage
